---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: order-capture-api
  labels:
    app: order-capture-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-capture-api
  template:
    metadata:
      labels:
        app: order-capture-api
    spec:
      containers:
      - name: order-capture-api
        image: "sabbour/captureorderack-netcore"
        ports:
        - containerPort: 8080
        env:
        - name: APPINSIGHTS_KEY
          value: ""
        - name: TEAMNAME
          value: "Toxic Cloud Architects"
        - name: AMQPURL
          value: "amqp://user:C4sWfv4eu7@doltish-robin-rabbitmq.default.svc.cluster.local:5672"
        - name: MONGOURL
          value: "mongodb://honking-wolverine-mongodb.default.svc.cluster.local:27017"

---
kind: Service
apiVersion: v1
metadata:
  name: order-capture-service
spec:
  type: LoadBalancer
  selector:
    app: order-capture-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
